create database clinica2021;
use clinica2021;

CREATE TABLE PACIENTES (
COD_PACIENTE VARCHAR(4),
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
DNI VARCHAR(9),
EDAD tinyint,
POBLACION VARCHAR(25),
CONSTRAINT PK_PACIENTES PRIMARY KEY(COD_PACIENTE))engine=INNODB;

CREATE TABLE MEDICOS (
NCOLEGIADOS VARCHAR(4),
NOMBRE VARCHAR(20),
APELLIDO VARCHAR(20),
ESPECIALIDAD varchar(20),
CARGO VARCHAR(20),
 constraint PK_MEDICOS PRIMARY  KEY (NCOLEGIADOS))engine=INNODB;
 
 
 
CREATE TABLE INGRESOS(
COD_INGRESOS VARCHAR(2),
FECHA_I DATE, 
FECHA_ALTA DATE,
URGENCIAS VARCHAR(1),
COSTE int,
DIAGNOSTICO VARCHAR(25),
COD_PACIENTE VARCHAR(4),
N_COLEGIADO VARCHAR(4),
CONSTRAINT PK_INGRESOS PRIMARY KEY(COD_INGRESOS),
CONSTRAINT FK_PACIENTES foreign key (COD_PACIENTE) REFERENCES PACIENTES (COD_PACIENTE),
CONSTRAINT FK_MEDICOS foreign key (N_COLEGIADO ) REFERENCES MEDICOS (NCOLEGIADOS)
) engine=INNODB;

INSERT INTO PACIENTES VALUES( '11','ELENA', 'GARCIA', '0198756',64, 'TOLEDO');    

INSERT INTO PACIENTES 
VALUES( '14','IVAN', 'ROL', '0058756',54, 'TOLEDO');
INSERT INTO PACIENTES 
VALUES( '15','ENCARNACION', 'PEREZ', '0058756',54, 'TOLEDO');
INSERT INTO PACIENTES 
VALUES( '16','INES', 'ROL', '0358756',14, 'TOLEDO');
INSERT INTO PACIENTES 
VALUES( '18','ELENA', 'PEREZ', '0358756',24, 'TOLEDO');
INSERT INTO PACIENTES 
VALUES( '19','BELEN', 'ROL', '0358756',14, 'TOLEDO');
INSERT INTO PACIENTES 
VALUES( '20','ANTONI', 'PEREZ', '0358756',24, 'MADRID');
INSERT INTO PACIENTES 
VALUES( '26','TEESA', 'PEREZ', '0358736',4, 'MADRID');



INSERT INTO `clinica2021`.`medicos` (`NCOLEGIADOS`, `NOMBRE`, `APELLIDO`, `ESPECIALIDAD`, `CARGO`) VALUES ('3333', 'ANTONIO', 'PULIDO', 'NEURO', 'JP');

INSERT INTO `clinica2021`.`medicos` (`NCOLEGIADOS`, `NOMBRE`, `APELLIDO`, `ESPECIALIDAD`, `CARGO`) VALUES ('4444', 'lUCIA', 'MAGAÑA', 'CARDIOLOGO', 'R1');

INSERT INTO `clinica2021`.`medicos` (`NCOLEGIADOS`, `NOMBRE`, `APELLIDO`, `ESPECIALIDAD`, `CARGO`) VALUES ('5555', 'HERNAN', 'MAGAÑA', 'NEURO', 'R1');

INSERT INTO clinica2021.ingresos
VALUES ('3', curdate(), '12/12/20', 'S', '2355', 'CEFALEAS', '14', '3333');
INSERT INTO clinica2021.ingresos 
VALUES ('4', curdate(), '12/12/20', 'S', '2355', 'CEFALEAS', '14', '4444');
INSERT INTO clinica2021.ingresos
VALUES ('6', curdate(), '12/12/20', 'S', '2355', 'CEFALEAS', '14', '5555');
